//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesProjectTickets.Application.Shared {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MessagesCentral {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessagesCentral() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SalesProjectTickets.Application.Shared.MessagesCentral", typeof(MessagesCentral).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario ya existe, verifique su correo y documento.
        /// </summary>
        internal static string MESSAGES_EXISTING_USER {
            get {
                return ResourceManager.GetString("MESSAGES_EXISTING_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La fecha no debe ser menor o igual a la actual.
        /// </summary>
        internal static string MESSAGES_GREATER_THAN_DATE {
            get {
                return ResourceManager.GetString("MESSAGES_GREATER_THAN_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiene que ser mayor a 0.
        /// </summary>
        internal static string MESSAGES_GREATER_THAN_ZERO {
            get {
                return ResourceManager.GetString("MESSAGES_GREATER_THAN_ZERO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correo electronico invalido .
        /// </summary>
        internal static string MESSAGES_INVALID_EMAIL {
            get {
                return ResourceManager.GetString("MESSAGES_INVALID_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo permite maximo 100 caracteres.
        /// </summary>
        internal static string MESSAGES_LENGTH {
            get {
                return ResourceManager.GetString("MESSAGES_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El documento debe tener 10 digitos.
        /// </summary>
        internal static string MESSAGES_LENGTH_DOCUMENT {
            get {
                return ResourceManager.GetString("MESSAGES_LENGTH_DOCUMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo debe tener entre 3 y 50 caracteres.
        /// </summary>
        internal static string MESSAGES_LENGTH_FIELDS {
            get {
                return ResourceManager.GetString("MESSAGES_LENGTH_FIELDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo solo admite letras.
        /// </summary>
        internal static string MESSAGES_ONLY_LETTERS {
            get {
                return ResourceManager.GetString("MESSAGES_ONLY_LETTERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo es requerido.
        /// </summary>
        internal static string MESSAGES_REQUERID_FIELDS {
            get {
                return ResourceManager.GetString("MESSAGES_REQUERID_FIELDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario no enconrado o credenciales malas.
        /// </summary>
        internal static string MESSAGES_VERIFY_USER {
            get {
                return ResourceManager.GetString("MESSAGES_VERIFY_USER", resourceCulture);
            }
        }
    }
}
