//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesProjectTickets.Application.Shared {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MessagesError {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessagesError() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SalesProjectTickets.Application.Shared.MessagesError", typeof(MessagesError).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El usuario ya existe, verifique su correo y documento.
        /// </summary>
        internal static string MESSAGES_EXISTING_USER {
            get {
                return ResourceManager.GetString("MESSAGES_EXISTING_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La fecha tiene que ser a futuro, no se permite la fecha actual o menor .
        /// </summary>
        internal static string MESSAGES_GREATER_THAN_DATE {
            get {
                return ResourceManager.GetString("MESSAGES_GREATER_THAN_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tiene que ser mayor a 0, no se permiten negativos.
        /// </summary>
        internal static string MESSAGES_GREATER_THAN_ZERO {
            get {
                return ResourceManager.GetString("MESSAGES_GREATER_THAN_ZERO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El email no es válido.
        /// </summary>
        internal static string MESSAGES_INVALID_EMAIL {
            get {
                return ResourceManager.GetString("MESSAGES_INVALID_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La descripción debe tener entre 5 a 255 caracteres.
        /// </summary>
        internal static string MESSAGES_LENGTH_DESCRIPTION {
            get {
                return ResourceManager.GetString("MESSAGES_LENGTH_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El documento de identidad debe tener 10 digitos.
        /// </summary>
        internal static string MESSAGES_LENGTH_DOCUMENT {
            get {
                return ResourceManager.GetString("MESSAGES_LENGTH_DOCUMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El apellido debe tener entre 3 a 50 caracteres.
        /// </summary>
        internal static string MESSAGES_LENGTH_LASTNAME {
            get {
                return ResourceManager.GetString("MESSAGES_LENGTH_LASTNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Maximo 255 caracteres.
        /// </summary>
        internal static string MESSAGES_LENGTH_LOCATION {
            get {
                return ResourceManager.GetString("MESSAGES_LENGTH_LOCATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El nombre debe tener entre 3 a 50 caracteres.
        /// </summary>
        internal static string MESSAGES_LENGTH_NAME {
            get {
                return ResourceManager.GetString("MESSAGES_LENGTH_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La fecha de creación no puede ser menor a la fecha actual.
        /// </summary>
        internal static string MESSAGES_MINOR_DATE {
            get {
                return ResourceManager.GetString("MESSAGES_MINOR_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La fecha de creación no puede ser mayor a la fecha actual.
        /// </summary>
        internal static string MESSAGES_OLDER_DATE {
            get {
                return ResourceManager.GetString("MESSAGES_OLDER_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El apellido solo puede contener letras.
        /// </summary>
        internal static string MESSAGES_ONLY_LETTERS_LASTNAME {
            get {
                return ResourceManager.GetString("MESSAGES_ONLY_LETTERS_LASTNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El nombre solo puede contener letras.
        /// </summary>
        internal static string MESSAGES_ONLY_LETTERS_NAME {
            get {
                return ResourceManager.GetString("MESSAGES_ONLY_LETTERS_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La descripción es requerida.
        /// </summary>
        internal static string MESSAGES_REQUERID_DESCRIPTION {
            get {
                return ResourceManager.GetString("MESSAGES_REQUERID_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El documento de identidad es requerido.
        /// </summary>
        internal static string MESSAGES_REQUERID_DOCUMENT {
            get {
                return ResourceManager.GetString("MESSAGES_REQUERID_DOCUMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El email es requerido.
        /// </summary>
        internal static string MESSAGES_REQUERID_EMAIL {
            get {
                return ResourceManager.GetString("MESSAGES_REQUERID_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El apellido es requerido.
        /// </summary>
        internal static string MESSAGES_REQUERID_LASTNAME {
            get {
                return ResourceManager.GetString("MESSAGES_REQUERID_LASTNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El lugar del evento es requerido.
        /// </summary>
        internal static string MESSAGES_REQUERID_LOCATION {
            get {
                return ResourceManager.GetString("MESSAGES_REQUERID_LOCATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El nombre es requerido.
        /// </summary>
        internal static string MESSAGES_REQUERID_NAME {
            get {
                return ResourceManager.GetString("MESSAGES_REQUERID_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La contraseña es requerida.
        /// </summary>
        internal static string MESSAGES_REQUERID_PASSWORD {
            get {
                return ResourceManager.GetString("MESSAGES_REQUERID_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El precio es requerido.
        /// </summary>
        internal static string MESSAGES_REQUERID_PRICE {
            get {
                return ResourceManager.GetString("MESSAGES_REQUERID_PRICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La cantidad es requerida.
        /// </summary>
        internal static string MESSAGES_REQUERID_QUANTITY {
            get {
                return ResourceManager.GetString("MESSAGES_REQUERID_QUANTITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario no enconrado o credenciales malas.
        /// </summary>
        internal static string MESSAGES_VERIFY_USER {
            get {
                return ResourceManager.GetString("MESSAGES_VERIFY_USER", resourceCulture);
            }
        }
    }
}
